### PR TITLE
Update parser.ts support fileName with wildcard

### PR DESCRIPTION
**Pull request by yiming0**
issue: #148

### CODE REVIEW

**Comment by endel** [comment]
Thanks for the PR @yiming0, this is indeed a Windows shell problem as you mentioned here https://github.com/colyseus/schema/issues/148

Let me give some feedback: 

- It's great you're not using an external dependency to evaluate the wildcard
- The ideal place for recursing on wildcard files would be during `generate()` function, before calling `parseFiles()`, here: https://github.com/colyseus/schema/blob/4b7410dd8f700ffc671af91802cac346de77bdf4/src/codegen/api.ts#L34
- After your PR, on OSX, most codegen tests are not passing now:

```
 2) schema-codegen
       should generate 3 files:

      AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:

3 !== 0

      + expected - actual

      -3
      +0

      at Context.<anonymous> (test/codegen/CodegenTest.ts:35:16)
      at processImmediate (node:internal/timers:476:21)

  3) schema-codegen
       should auto-import related schema files:

      AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:

2 !== 0

      + expected - actual

      -2
      +0

      at Context.<anonymous> (test/codegen/CodegenTest.ts:61:16)
      at processImmediate (node:internal/timers:476:21)

  4) schema-codegen
       should support using 'type' along with `defineTypes`:

      AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:

1 !== 0

      + expected - actual

      -1
      +0

      at Context.<anonymous> (test/codegen/CodegenTest.ts:73:16)
      at processImmediate (node:internal/timers:476:21)

  5) schema-codegen
       should support generating abstract classes with no fields:

      AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:

2 !== 0

      + expected - actual

      -2
      +0

      at Context.<anonymous> (test/codegen/CodegenTest.ts:87:16)
      at processImmediate (node:internal/timers:476:21)

  6) schema-codegen
       should support generating enums:

      AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:

2 !== 0

      + expected - actual

      -2
      +0

      at Context.<anonymous> (test/codegen/CodegenTest.ts:99:16)
      at processImmediate (node:internal/timers:476:21)

```

**Comment by yiming0** [comment]
> Thanks for the PR @yiming0, this is indeed a Windows shell problem as you mentioned here #148
> 
> Let me give some feedback:
> 
> * It's great you're not using an external dependency to evaluate the wildcard
> * The ideal place for recursing on wildcard files would be during `generate()` function, before calling `parseFiles()`, here: https://github.com/colyseus/schema/blob/4b7410dd8f700ffc671af91802cac346de77bdf4/src/codegen/api.ts#L34
> * After your PR, on OSX, most codegen tests are not passing now:

🙁 well, i'm going to fix that

**Comment by yiming0** [comment]
here is test result: https://github.com/yiming0/colyseus-schema/actions/runs/4987664125

**Comment by endel** [comment]
This is excellent! Thank you! 💖

**Pull request merged**
